CREATE TABLE users (
   id VARCHAR(36) PRIMARY KEY,
   status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',

   name VARCHAR(255) NOT NULL,
   email VARCHAR(255) NOT NULL UNIQUE,
   password VARCHAR(255) NOT NULL,
   email_verified BOOLEAN NOT NULL DEFAULT FALSE,
   role VARCHAR(50) NOT NULL,

   created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
   created_by VARCHAR(255),
   updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
   updated_by VARCHAR(255),
   version            BIGINT NOT NULL DEFAULT 0
);

CREATE INDEX idx_users_email ON users(email);